#!/bin/bash

#dependencies
sudo apt-get update
sudo apt-get install git
sudo apt-get install python-pip
sudo pip install google-api-python-client
sudo pip install gspread

repoPATH="/home/ubuntu/forgescan.github.io"

#install Xvfb  #this is the virtual frame buffer
apt-get install imagemagick xvfb



#Install Chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update 
sudo apt-get install google-chrome-stable




sudo mkdir $repoPATH  #/home/ubuntu/forgescan.github.io


sudo git clone https://github.com/forgescan/forgescan.github.io
# so this brings in the repo


#set up chrome #allow to run in root
sudo rm /opt/google/chrome/google-chrome 
subdir= HAPYAKDEMOMAKERINSTALL/google-chrome
sudo cp $repoPATH/$subdir /opt/google/chrome/google-chrome  

 


#this creates the service which runs on boot
sudo cp $repoPATH/HAPYAKDEMOMAKERINSTALL/hapyak /etc/init.d/hapyak  
sudo update-rc.d hapyak default
sudo chmod 777 /etc/init.d/hapyak
sudo chmod 777 -R $repoPATH

#git needs to be setup to login automatically and the json key must be added manually
#so to set up git to run automatically add a 

